feature/full-task
yyyrk/TheGuruProject pull request #7
Opened 2024-12-16 04:18 UTC by yyyrk

запрос на добавление

2024-12-16 14:27 UTC, VidgarVii requested changes

2024-12-16 14:27 UTC, VidgarVii commented on README.md
> +5. Результаты прохождения тестов
Еще не хвататет - Категория. Нужны для типов тестов по категориям

2024-12-16 14:27 UTC, VidgarVii commented on app/controllers/static_pages_controller.rb
> +class StaticPagesController < ApplicationController
`html` файлы целиком статические
их будет оптимальнее отдать вообще в обход рельсового приложения (так будет работать быстрее, да и рельсам с этими файлами делать то нечего)
для этого их достаточно поместить в директорию `public`

роуты при этом не нужны и контроллеры тоже
(путь к файлу внутри директории `public` должен соответствовать пути, по которому этот файл должен быть доступен)

2024-12-16 14:28 UTC, VidgarVii requested changes

2024-12-16 14:28 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.default_locale = :ru # устанавливаю локализацию
чтобы не было ошибок в системе, надо еще добавить файл конфигураций в папку config/locales ru.yml. Содержание почти аналогичное как en.yml

2024-12-17 04:40 UTC, yyyrk commented on app/controllers/static_pages_controller.rb
> +class StaticPagesController < ApplicationController
Исправил. Написал в комментарии chore, но потом понял, что это perf коммит.

2024-12-17 04:41 UTC, yyyrk commented on config/application.rb
> +    config.i18n.default_locale = :ru # устанавливаю локализацию
Добавил

2024-12-17 04:41 UTC, yyyrk commented on README.md
> +5. Результаты прохождения тестов
Поправил

2024-12-17 04:56 UTC, VidgarVii requested changes

2024-12-17 04:56 UTC, VidgarVii commented on config/routes.rb
> +  # get '/about', to: 'static_pages#about'
данный код надо удалять, а не комментировать

2024-12-17 04:56 UTC, VidgarVii commented on config/locales/ru.yml
> +        blank: "не может быть пустым"
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file. Многие компиляторы тут выдадут ошибку. Руби частично компилируемый язык. И такой разрыв легко проглотит. Но в реальных проектах это как красная тряпка для быка. Так что тренируем дисциплину и больше такого не совершаем! В руби за чистоту кода!

2024-12-17 04:56 UTC, VidgarVii commented on app/controllers/static_pages_controller.rb
> +class StaticPagesController < ApplicationController
этот файл надо удалить

2024-12-17 04:56 UTC, VidgarVii commented on app/helpers/static_pages_helper.rb
> +module StaticPagesHelper
и этот файл не нужен

2024-12-17 04:56 UTC, VidgarVii commented on public/about.html
> +<!--<p>Узнать больше можно на сайте моей школы <a href="http://www.thinknetica.com" target="_blank">Thinknetica</a>.</p>-->
подобные комменты пользы не несут. стоит их удалить

2024-12-17 04:56 UTC, VidgarVii commented on public/about/author.html
> +<!--<p>GitHub автора: <a href="https://github.com/yyyrk" target="_blank">github.com/yyyrk</a>.</p>-->
подобные комменты пользы не несут. стоит их удалить

2024-12-17 04:56 UTC, VidgarVii commented on test/controllers/static_pages_controller_test.rb
> +require "test_helper"
этот файл не нужен

2024-12-17 08:57 UTC, yyyrk commented on public/about/author.html
> +<!--<p>GitHub автора: <a href="https://github.com/yyyrk" target="_blank">github.com/yyyrk</a>.</p>-->
Удалил файл static_pages_controller_test.rb

2024-12-17 08:59 UTC, yyyrk commented on public/about.html
> +<!--<p>Узнать больше можно на сайте моей школы <a href="http://www.thinknetica.com" target="_blank">Thinknetica</a>.</p>-->
Удалил комментарии

2024-12-17 09:19 UTC, andreiyurik commented on config/locales/ru.yml
> +        blank: "не может быть пустым"
Поправил.

2024-12-17 15:31 UTC, BubuntuClu commented on config/routes.rb
> +  get "static_pages/about"
контроллер и вьюхи ты уже удалил. роут тоже надо удалить, статичные публичные страницы доступны без роутинга, приложение само понимает как их отдать

2024-12-17 15:31 UTC, BubuntuClu commented on public/about.html
> +    <style>
стоит разделять файлы со стилями и html кодом по разным папкам, в публичных страницах это не критично. в последующем в проекте надо будем делать с учетом деления кода по папкам

2024-12-18 03:03 UTC, yyyrk commented on public/about.html
> +    <style>
Да, это пока временное решение, чтобы чистый html глаз не резал

2024-12-18 03:06 UTC, yyyrk commented on test/controllers/static_pages_controller_test.rb
> +require "test_helper"
Все, удалил test_helper

2024-12-20 14:02 UTC, merged